####################################################################
#### run-deployment-report.yml                                  ####
####################################################################
#### Author: SAS Institute Inc.                                 ####
####################################################################

####################################################################
#
# This playbook gathers information about SAS software installed on
# the hosts in the given inventory file as well as a snapshot of
# some system resources, like memory and filesystem usage. This
# playbook does not alter state on any host except for the Ansible
# controller where the .yml and .html files are written.
#
####################################################################

---
- import_playbook: ../common/handle_hostgroup_hyphens.yml
  tags:
    - always

- name: "Viya Deployment Report"
  hosts: sas_all

  vars:
    # These variables can be safely overridden on the commandline
    existing_data_file: ""
    include_package_files: false
    exclude_html: false
    report_file_name: "viya_deployment_report"
    report_data_file_name: "{{ report_file_name + '_data' }}"
    output_dir: "{{ playbook_dir + '/../../..' }}"

  tasks:
    - name: "Check for existing data - ({{ existing_data_file }})"
      stat:
        path: "{{ existing_data_file }}"
      delegate_to: localhost
      run_once: true
      register: data
      when: existing_data_file != ""

    - name: "Load existing data file"
      include_vars:
        file: "{{ existing_data_file }}"
        name: sas_deployment_details
      delegate_to: localhost
      delegate_facts: true
      run_once: true
      when: existing_data_file != "" and data.stat.exists

    - name: "Get SAS host details"
      get_sas_host_details:
        hostvars: "{{ hostvars[inventory_hostname] }}"
        include_package_files: "{{ include_package_files }}"
      become: true
      when: existing_data_file == "" or not data.stat.exists
      register: get_sas_host_details_results

    - name: "Process SAS host details"
      process_sas_host_details:
        hostvars: "{{ hostvars }}"
        report_timestamp: "{{ '%A, %B %d, %Y %I:%M%p'|strftime(ansible_date_time.epoch) }}"
        registered_dict_name: 'get_sas_host_details_results'
      delegate_to: localhost
      run_once: true
      register: process_sas_host_details_results
      when: existing_data_file == "" or not data.stat.exists

    - set_fact:
        sas_deployment_details: "{{ process_sas_host_details_results.processed_host_details }}"
      delegate_to: localhost
      delegate_facts: true
      run_once: true
      when: existing_data_file == "" or not data.stat.exists

    - set_fact:
        sas_viya_deployment_report_file: "{{ output_dir | realpath }}/{{ report_file_name + '_' + '%F_%H-%M-%S'|strftime(ansible_date_time.epoch) + '.html' }}"
        sas_viya_deployment_report_data_file: "{{ output_dir | realpath }}/{{ report_data_file_name + '_' + '%F_%H-%M-%S'|strftime(ansible_date_time.epoch) + '.yml' }}"
      delegate_to: localhost
      delegate_facts: true
      run_once: true

    - name: "Create Viya Deployment Report data file"
      copy:
        content: "{{ hostvars['localhost']['sas_deployment_details'] | to_nice_yaml }}"
        dest: "{{ hostvars['localhost']['sas_viya_deployment_report_data_file'] }}"
        mode: 0640
      delegate_to: localhost
      run_once: true
      when: existing_data_file == "" or not data.stat.exists

    - name: "Viya Deployment Report Data location"
      debug:
        msg: "Created {{ hostvars['localhost']['sas_viya_deployment_report_data_file'] }}"
      delegate_to: localhost
      run_once: true
      when: existing_data_file == "" or not data.stat.exists

    - name: "Create Viya Deployment HTML Report"
      template:
        src: templates/viya_deployment_report.html.j2
        dest: "{{ hostvars['localhost']['sas_viya_deployment_report_file'] }}"
        mode: 0640
      delegate_to: localhost
      run_once: true
      when: not exclude_html

    - name: "Viya Deployment Report location"
      debug:
        msg: "Created {{ hostvars['localhost']['sas_viya_deployment_report_file'] }}"
      delegate_to: localhost
      run_once: true
      when: not exclude_html
