####################################################################
#### viya-services-disable.yml                                  ####
####################################################################
#### Author: SAS Institute Inc.                                 ####
####################################################################
---
- import_playbook: ../common/handle_hostgroup_hyphens.yml
  tags:
    - always

- hosts: sas_all
  become: yes
  become_user: root
  gather_facts: False
  any_errors_fatal: true

  tasks:
    - name: Disable SAS Viya all services from system reboot
      service:
        name: sas-viya-all-services
        enabled: no
